# -*- coding: utf-8 -*-
"""NeuSOGA3D-demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uW728puHTC4NNHNiuD1U1VESLfRUpia-
"""

# =====================================================================
# 0. KERNEL RESET REQUIRED / AUTO-INSTALLER & STRICT IMPORT HIERARCHY
# =====================================================================
import sys
import subprocess

try:
    import segment_anything
except ImportError:
    print("Installing official 'segment_anything' library from Meta's GitHub...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "git+https://github.com/facebookresearch/segment-anything.git"])

import torch
import torch.nn
import torch.nn.functional as F
from segment_anything import sam_model_registry, SamPredictor

import os
import urllib.request
import zipfile
import h5py
import numpy as np
import cv2
import math
import matplotlib.pyplot as plt
from matplotlib.colors import LightSource
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import scipy.ndimage as ndi
from scipy.ndimage import gaussian_filter
from skimage.measure import approximate_polygon, marching_cubes, find_contours
from skimage.feature import peak_local_max
from numba import njit, prange

# =====================================================================
# 1. PLATONIST MATH ENGINE: NEUSOGA PSPS EXPLICIT FORMULATION
# =====================================================================
@njit
def fact(n):
    res = 1
    for i in range(1, n + 1): res *= i
    return res

@njit
def comb_numba(n, k):
    if k < 0 or k > n: return 0
    if k == 0 or k == n: return 1
    return fact(n) // (fact(k) * fact(n - k))

@njit
def FF_scalar(s, n):
    if n == 0: return 0.5 if s == 0.0 else (1.0 if s > 0.0 else 0.0)
    else: return (s / n) * FF_scalar(s, n-1) + (1.0 - s/n) * FF_scalar(s-1, n-1)

@njit
def H_scalar(s, n):
    if n == 0: return FF_scalar(s, 0)
    else: return FF_scalar(n * (s + 1.0) / 2.0, n)

@njit
def evaluate_PSPS_step(y, y_start, y_end, n, transition_delta):
    if y <= y_start: return 0.0
    if y >= y_end: return 1.0
    t = (y - y_start) / (y_end - y_start)
    s = (2.0 * t - 1.0) / transition_delta
    if s <= -1.0: return 0.0
    if s >= 1.0: return 1.0
    return H_scalar(s, n)

@njit
def evaluate_PSPS_basis(y, knots, i, n, transition_delta):
    N = len(knots)
    if i == 0: H_prev = 1.0
    else: H_prev = evaluate_PSPS_step(y, knots[i-1], knots[i], n, transition_delta)
    if i == len(knots) - 1: H_curr = 0.0
    else: H_curr = evaluate_PSPS_step(y, knots[i], knots[i+1], n, transition_delta)
    return H_prev - H_curr

@njit
def Lxy_scalar(x, y, slope, n):
    if slope * x > y: return ((slope * x - y)**(2*n)) / (fact(2*n) * (slope**n))
    return 0.0

@njit
def Lxy00_scalar(x, y, slope, n):
    AA = 0.0
    for k in range(1, n+1):
        AA += ((-1.0)**(n+k) * (x**(n-k)) * (y**(n+k))) / (fact(n-k) * fact(n+k) * (slope**k))
    return AA

@njit
def L_corner_inter_scalar(x, y, slope, n):
    slope = abs(slope)
    if n < 1: return 0.0
    if y < min(0.0, slope * x):
        return Lxy_scalar(x, y, slope, n) if x <= 0.0 else Lxy00_scalar(x, y, slope, n)
    return 0.0

@njit
def U_Angle_inter_scalar(x, y, slope, delta, n):
    FF_val = 0.0
    for k in range(0, n+1):
        FF_val += (-1.0)**k * comb_numba(n, k) * L_corner_inter_scalar(x + (n - 2*k)*delta, y, slope, n)
    return FF_val

@njit
def impAngle4BigSlope_scalar(x, y, slope, delta, n):
    GG = 0.0
    for k in range(0, n+1):
        GG += (-1.0)**k * comb_numba(n, k) * U_Angle_inter_scalar(x, y - (n - 2*k)*delta, slope, delta, n)
    return GG / ((4.0 * delta**2)**n)

@njit
def Square_Angle_inter_scalar(x, y, slope, delta, n):
    if slope > 1.0: return impAngle4BigSlope_scalar(x, y, slope, delta, n)
    else: return H_scalar(-x/(n*delta), n) * H_scalar(-y/(n*delta), n) - impAngle4BigSlope_scalar(y, x, 1.0/slope, delta, n)

@njit
def Point_imp_scalar(x, y, x0, y0, slope, delta, n):
    if math.isinf(slope): return 0.0
    if abs(slope) < 1e-32: return H_scalar((x0-x)/(n*delta), n) * H_scalar((y0-y)/(n*delta), n)
    if slope >= 1e-32: return Square_Angle_inter_scalar(x-x0, y-y0, slope, delta, n)
    else: return Square_Angle_inter_scalar(-(x-x0), y-y0, -slope, delta, n)

@njit
def LineSeg_imp_scalar(x, y, x0, y0, x1, y1, delta, n):
    y01, x01 = y1 - y0, x1 - x0
    if x01 == 0.0: return 0.0
    slope = y01 / x01
    if slope == 0.0:
        if x01 > 0.0: return Point_imp_scalar(x, y, x1, y1, slope, delta, n) - Point_imp_scalar(x, y, x0, y0, slope, delta, n)
        else: return Point_imp_scalar(x, y, x0, y0, slope, delta, n) - Point_imp_scalar(x, y, x1, y1, slope, delta, n)
    if y01 > 0.0: return Point_imp_scalar(x, y, x1, y1, slope, delta, n) - Point_imp_scalar(x, y, x0, y0, slope, delta, n)
    else: return Point_imp_scalar(x, y, x0, y0, slope, delta, n) - Point_imp_scalar(x, y, x1, y1, slope, delta, n)

@njit(parallel=True)
def ImpSpline2D(xx, yy, data, delta=0.01, n=2):
    rows, cols = xx.shape
    imp2DFun = np.zeros((rows, cols), dtype=np.float64)
    NumP = data.shape[0]

    for i in prange(rows):
        for j in range(cols):
            x, y = xx[i, j], yy[i, j]
            val = 0.0
            for p in range(NumP):
                x0, y0 = data[p, 0], data[p, 1]
                x1, y1 = data[(p+1)%NumP, 0], data[(p+1)%NumP, 1]
                xDir = x0 - x1
                if xDir > 0: sign_val = 1.0
                elif xDir < 0: sign_val = -1.0
                else: sign_val = 0.0
                if sign_val != 0.0:
                    val += sign_val * LineSeg_imp_scalar(x, y, x0, y0, x1, y1, delta, n)
            imp2DFun[i, j] = val
    return imp2DFun

@njit
def soft_abs2(x, a):
    xx = 2.0 * x / a
    abs2 = abs(xx)
    if abs2 < 2.0: return 0.5 * (xx ** 2) * (1.0 - abs2 / 6.0) + 2.0 / 3.0
    else: return abs2

@njit
def soft_min2(x, y, a=0.03):
    return 0.5 * (x + y - soft_abs2(x - y, a) * a / 2.0)

@njit(parallel=True)
def apply_softMin2_3D(volA, volB, eps=0.05):
    d0, d1, d2 = volA.shape
    out = np.zeros((d0, d1, d2), dtype=np.float64)
    for i in prange(d0):
        for j in range(d1):
            for k in range(d2):
                out[i, j, k] = soft_min2(volA[i, j, k], volB[i, j, k], eps)
    return out

# =====================================================================
# 2. DATASET DOWNLOADER
# =====================================================================
def download_modelnet40():
    url = "https://huggingface.co/datasets/Msun/modelnet40/resolve/main/modelnet40_ply_hdf5_2048.zip"
    zip_path = "modelnet40.zip"
    extract_folder = "modelnet40_data"
    if not os.path.exists(extract_folder):
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as response, open(zip_path, 'wb') as out_file:
            out_file.write(response.read())
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_folder)
        os.remove(zip_path)
    return os.path.join(extract_folder, "modelnet40_ply_hdf5_2048")

def initialize_sam():
    print("Loading Meta Segment Anything Model (SAM)...")
    sam_checkpoint = "sam_vit_b_01ec64.pth"
    if not os.path.exists(sam_checkpoint):
        url = "https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth"
        urllib.request.urlretrieve(url, sam_checkpoint)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    sam = sam_model_registry["vit_b"](checkpoint=sam_checkpoint)
    sam.to(device=device)
    return SamPredictor(sam)

# =====================================================================
# 3. ROBUST NEUSOGA CROSS-SECTIONAL SLICE EXTRACTION S_i
# =====================================================================
def process_contour_hybrid(c, x_min, x_max, y_min, y_max, img_size):
    coarse_x = gaussian_filter(c[:, 0].astype(float), sigma=6.0, mode='wrap')
    coarse_y = gaussian_filter(c[:, 1].astype(float), sigma=6.0, mode='wrap')
    curve_coarse = np.column_stack((coarse_x, coarse_y))
    fine_x = gaussian_filter(c[:, 0].astype(float), sigma=1.5, mode='wrap')
    fine_y = gaussian_filter(c[:, 1].astype(float), sigma=1.5, mode='wrap')
    curve_fine = np.column_stack((fine_x, fine_y))

    deviation = np.linalg.norm(curve_coarse - curve_fine, axis=1)
    missed_mask = (deviation > 2.0).astype(float)
    blend_weight = gaussian_filter(missed_mask, sigma=3.0, mode='wrap')
    blend_weight = np.clip(blend_weight, 0, 1).reshape(-1, 1)

    hybrid_curve = curve_coarse * (1.0 - blend_weight) + curve_fine * blend_weight
    sampled = approximate_polygon(hybrid_curve, tolerance=0.8)

    if len(sampled) < 3: return np.empty((0, 2))
    if np.linalg.norm(sampled[0] - sampled[-1]) < 1e-5: sampled = sampled[:-1]
    if len(sampled) < 3: return np.empty((0, 2))

    x_coords = x_min + (sampled[:, 0] / (img_size - 1)) * (x_max - x_min)
    y_coords = y_min + ((img_size - 1 - sampled[:, 1]) / (img_size - 1)) * (y_max - y_min)
    poly = np.column_stack((x_coords, y_coords))

    x_pts, y_pts = poly[:, 0], poly[:, 1]
    signed_area = np.sum(x_pts[:-1] * y_pts[1:] - x_pts[1:] * y_pts[:-1]) + (x_pts[-1] * y_pts[0] - x_pts[0] * y_pts[-1])
    if signed_area < 0: poly = poly[::-1]
    return poly

def holistic_hybrid_extraction(pc_2d, predictor, img_size=512, margin=0.15):
    # [CRITICAL FIX]: Force Aspect Ratio Preservation
    # Prevents SAM from stretching the side/front view into an unrecognizable square
    x_min, x_max = pc_2d[:, 0].min() - margin, pc_2d[:, 0].max() + margin
    y_min, y_max = pc_2d[:, 1].min() - margin, pc_2d[:, 1].max() + margin
    max_range = max(x_max - x_min, y_max - y_min)

    x_center = (x_max + x_min) / 2.0
    y_center = (y_max + y_min) / 2.0

    x_min, x_max = x_center - max_range / 2.0, x_center + max_range / 2.0
    y_min, y_max = y_center - max_range / 2.0, y_center + max_range / 2.0

    img_gray = np.zeros((img_size, img_size), dtype=np.uint8)
    for p in pc_2d:
        px = int(((p[0] - x_min) / (x_max - x_min)) * (img_size - 1))
        py = int(((p[1] - y_min) / (y_max - y_min)) * (img_size - 1))
        cv2.circle(img_gray, (px, py), radius=5, color=255, thickness=-1)

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (11, 11))
    mask_solid = cv2.morphologyEx(img_gray, cv2.MORPH_CLOSE, kernel)
    mask_flipped = cv2.flip(mask_solid, 0)
    predictor.set_image(cv2.cvtColor(mask_flipped, cv2.COLOR_GRAY2RGB))

    dist_transform = cv2.distanceTransform(mask_flipped, cv2.DIST_L2, 5)
    local_max_coords = peak_local_max(dist_transform, min_distance=8, threshold_abs=0.05 * dist_transform.max())

    if len(local_max_coords) == 0:
        _, _, _, max_loc = cv2.minMaxLoc(dist_transform)
        prompts = np.array([[max_loc[0], max_loc[1]]])
    else: prompts = np.array([[c[1], c[0]] for c in local_max_coords])

    masks, _, _ = predictor.predict(point_coords=prompts, point_labels=np.ones(len(prompts)), multimask_output=False)
    features = []

    if len(masks) > 0:
        mask_binary = (masks[0] * 255).astype(np.uint8)
        if mask_binary[0, 0] > 128 and mask_binary[img_size-1, img_size-1] > 128:
            mask_binary = cv2.bitwise_not(mask_binary)

        contours, _ = cv2.findContours(mask_binary, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for idx, c in enumerate(contours):
            if cv2.contourArea(c) < 5: continue
            c = c.reshape(-1, 2)
            c = c[np.insert(np.sum(np.abs(np.diff(c, axis=0)), axis=1) > 0, 0, True)]
            if len(c) >= 10:
                poly = process_contour_hybrid(c, x_min, x_max, y_min, y_max, img_size)
                if len(poly) > 0: features.append({'polygon': poly})

    if len(features) == 0:
        contours, _ = cv2.findContours(mask_flipped, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for idx, c in enumerate(contours):
            if cv2.contourArea(c) < 5: continue
            c = c.reshape(-1, 2)
            if len(c) >= 3:
                poly = process_contour_hybrid(c, x_min, x_max, y_min, y_max, img_size)
                if len(poly) > 0: features.append({'polygon': poly})

    return features

def generate_sam_implicit_field_2d(pc_2d, predictor, grid_size, bounds):
    xx, yy = np.meshgrid(np.linspace(bounds[0], bounds[1], grid_size),
                         np.linspace(bounds[0], bounds[1], grid_size), indexing='ij')
    full_field = np.zeros((grid_size, grid_size), dtype=np.float64)
    if len(pc_2d) < 5: return full_field

    features = holistic_hybrid_extraction(pc_2d, predictor, img_size=512)
    for feature in features:
        spline = np.abs(ImpSpline2D(xx, yy, feature['polygon'], delta=0.015, n=2))
        full_field += spline
    return np.clip(full_field, 0.0, 1.0)

def generate_solid_area_slice(pts_2d, grid_size, bounds):
    if len(pts_2d) < 3: return np.zeros((grid_size, grid_size), dtype=np.float64)

    img_size = 512
    binary_canvas = np.zeros((img_size, img_size), dtype=np.uint8)

    x_coords = ((pts_2d[:, 0] - bounds[0]) / (bounds[1] - bounds[0]) * (img_size - 1)).astype(int)
    y_coords = ((pts_2d[:, 1] - bounds[0]) / (bounds[1] - bounds[0]) * (img_size - 1)).astype(int)
    x_coords = np.clip(x_coords, 0, img_size - 1)
    y_coords = np.clip(y_coords, 0, img_size - 1)

    for x, y in zip(x_coords, y_coords):
        cv2.circle(binary_canvas, (x, y), radius=6, color=255, thickness=-1)

    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (15, 15))
    closed = cv2.morphologyEx(binary_canvas, cv2.MORPH_CLOSE, kernel)

    kernel_dilate = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5, 5))
    dilated = cv2.dilate(closed, kernel_dilate)

    solid_mask = ndi.binary_fill_holes(dilated > 0).astype(np.uint8) * 255
    contours, _ = cv2.findContours(solid_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    xx, yy = np.meshgrid(np.linspace(bounds[0], bounds[1], grid_size),
                         np.linspace(bounds[0], bounds[1], grid_size), indexing='ij')
    F_total = np.zeros((grid_size, grid_size), dtype=np.float64)
    has_valid = False

    for contour in contours:
        if cv2.contourArea(contour) < 1.0: continue
        poly = cv2.approxPolyDP(contour, epsilon=0.8, closed=True)

        if len(poly) >= 3:
            poly_data = poly.reshape(-1, 2).astype(np.float64)
            poly_physical = bounds[0] + (poly_data / (img_size - 1)) * (bounds[1] - bounds[0])
            F_poly = np.abs(ImpSpline2D(xx, yy, poly_physical, delta=0.04, n=2))
            F_total = np.maximum(F_total, np.clip(F_poly, 0.0, 1.0))
            has_valid = True

    if not has_valid: return np.zeros((grid_size, grid_size), dtype=np.float64)
    return F_total

# =====================================================================
# 4. EXPLICIT FORMULATION F(x,y,z) = sum_i S_i * B_i
# =====================================================================
def build_explicit_psps_loft(voxel_pts, slice_axis, grid_size, num_slices, bounds):
    perp_axes = [i for i in [0, 1, 2] if i != slice_axis]
    pos_min, pos_max = np.min(voxel_pts[:, slice_axis]), np.max(voxel_pts[:, slice_axis])

    base_positions = np.linspace(pos_min, pos_max, num_slices)
    step = (pos_max - pos_min) / max(num_slices - 1, 1)
    half_window = 1.8 * step

    slice_fields = []
    slice_fields.append(np.zeros((grid_size, grid_size), dtype=np.float64))

    for center in base_positions:
        mask = (voxel_pts[:, slice_axis] >= center - half_window) & (voxel_pts[:, slice_axis] <= center + half_window)
        pts_in_slice = voxel_pts[mask]
        slice_fields.append(generate_solid_area_slice(pts_in_slice[:, perp_axes], grid_size, bounds))

    slice_fields.append(np.zeros((grid_size, grid_size), dtype=np.float64))
    slice_positions = np.concatenate(([pos_min - step], base_positions, [pos_max + step]))
    total_slices = len(slice_positions)

    F_cyl = np.zeros((grid_size, grid_size, grid_size), dtype=np.float64)
    axis_coords = np.linspace(bounds[0], bounds[1], grid_size)

    for i_coord in range(grid_size):
        val = axis_coords[i_coord]
        F_val = np.zeros((grid_size, grid_size), dtype=np.float64)
        for i in range(total_slices):
            B_i = evaluate_PSPS_basis(val, slice_positions, i, 2, transition_delta=1.0)
            if B_i > 0: F_val += B_i * slice_fields[i]

        if slice_axis == 0: F_cyl[i_coord, :, :] = F_val
        elif slice_axis == 1: F_cyl[:, i_coord, :] = F_val
        else: F_cyl[:, :, i_coord] = F_val

    return F_cyl

def run_pure_implicit_reconstruction(pc_3d, predictor, grid_size=110, num_slices=36, blend_eps=0.03):
    bounds = (-1.3, 1.3)

    print("  -> Evaluating Orthographic Constraints (For Plotting)...")
    F_top_2d   = generate_sam_implicit_field_2d(pc_3d[:, [0, 1]], predictor, grid_size, bounds)
    F_front_2d = generate_sam_implicit_field_2d(pc_3d[:, [0, 2]], predictor, grid_size, bounds)
    F_side_2d  = generate_sam_implicit_field_2d(pc_3d[:, [1, 2]], predictor, grid_size, bounds)

    print("  -> Computing F_x(x,y,z) = Sum[ S_i(y,z) B_i(x) ]...")
    F_x = build_explicit_psps_loft(pc_3d, 0, grid_size, num_slices, bounds)

    print("  -> Computing F_y(x,y,z) = Sum[ S_i(x,z) B_i(y) ]...")
    F_y = build_explicit_psps_loft(pc_3d, 1, grid_size, num_slices, bounds)

    print("  -> Computing F_z(x,y,z) = Sum[ S_i(x,y) B_i(z) ]...")
    F_z = build_explicit_psps_loft(pc_3d, 2, grid_size, num_slices, bounds)

    print("  -> Fusing Implicit Volumes: F_final = F_x ∩ F_y ∩ F_z...")
    F_final = apply_softMin2_3D(F_x, F_y, eps=blend_eps)
    F_final = apply_softMin2_3D(F_final, F_z, eps=blend_eps)

    return F_final, F_x, F_y, F_z, (F_top_2d, F_front_2d, F_side_2d)

# =====================================================================
# 5. PUBLICATION-READY FIGURE GENERATION (1x3 Panel Layout)
# =====================================================================
def get_phong_facecolors(vertices, faces, color_hex, elev, azim):
    h = color_hex.lstrip('#')
    base_color = np.array([int(h[i:i+2], 16) / 255.0 for i in (0, 2, 4)])

    view_dir = np.array([
        math.cos(math.radians(elev)) * math.cos(math.radians(azim)),
        math.cos(math.radians(elev)) * math.sin(math.radians(azim)),
        math.sin(math.radians(elev))
    ])

    light_elev = elev + 40
    light_azim = azim - 30
    light_dir = np.array([
        math.cos(math.radians(light_elev)) * math.cos(math.radians(light_azim)),
        math.cos(math.radians(light_elev)) * math.sin(math.radians(light_azim)),
        math.sin(math.radians(light_elev))
    ])

    v0, v1, v2 = vertices[faces[:, 0]], vertices[faces[:, 1]], vertices[faces[:, 2]]
    normals = np.cross(v1 - v0, v2 - v0)
    norms = np.linalg.norm(normals, axis=1, keepdims=True)
    norms[norms == 0] = 1e-5
    normals = normals / norms

    dot_view = np.sum(normals * view_dir, axis=1)
    normals[dot_view < 0] *= -1

    diffuse = np.clip(np.sum(normals * light_dir, axis=1), 0, 1)

    half_vec = light_dir + view_dir
    half_vec = half_vec / np.linalg.norm(half_vec)
    spec_dot = np.clip(np.sum(normals * half_vec, axis=1), 0, 1)
    specular = np.power(spec_dot, 25.0)

    ambient = 0.45
    intensity = ambient + 0.65 * diffuse

    colors = np.zeros((len(faces), 4))
    for i in range(3):
        colors[:, i] = np.clip(base_color[i] * intensity + 0.55 * specular, 0, 1)
    colors[:, 3] = 1.0
    return colors


def generate_1x3_paper_figure(pc_3d, F_final, F_views, grid_size, bounds=(-1.3, 1.3)):
    print("\n  -> Rendering 1x3 Paper Figure Layout...")

    fig = plt.figure(figsize=(15, 5), facecolor='white')

    # Elegant 3/4 Aviation View Pointing Up-and-Right
    view_elev, view_azim = 25, -60

    def format_ax(ax, title):
        ax.view_init(elev=view_elev, azim=view_azim)
        ax.set_xlim(bounds); ax.set_ylim(bounds); ax.set_zlim(bounds)
        ax.set_box_aspect([1,1,1])
        ax.set_xticks([]); ax.set_yticks([]); ax.set_zticks([])
        ax.xaxis.pane.fill = False; ax.yaxis.pane.fill = False; ax.zaxis.pane.fill = False
        ax.xaxis.pane.set_edgecolor('white'); ax.yaxis.pane.set_edgecolor('white'); ax.zaxis.pane.set_edgecolor('white')
        ax.grid(False)
        ax.set_title(title, fontweight='bold', fontsize=12, pad=5)

        c = 'lightgray'
        ax.plot([bounds[0], bounds[1]], [bounds[0], bounds[0]], [bounds[0], bounds[0]], color=c, lw=0.5)
        ax.plot([bounds[0], bounds[0]], [bounds[0], bounds[1]], [bounds[0], bounds[0]], color=c, lw=0.5)
        ax.plot([bounds[0], bounds[0]], [bounds[0], bounds[0]], [bounds[0], bounds[1]], color=c, lw=0.5)

    def get_mesh(vol):
        try:
            v, f, _, _ = marching_cubes(vol, level=0.5)
            scale = (bounds[1] - bounds[0]) / (grid_size - 1)
            v = v * scale + bounds[0]
            return v, f
        except ValueError:
            return np.empty((0, 3)), np.empty((0, 3))

    def add_shaded_mesh(ax, vertices, faces, color_hex):
        if len(vertices) == 0: return
        colors = get_phong_facecolors(vertices, faces, color_hex, view_elev, view_azim)
        mesh = Poly3DCollection(vertices[faces], facecolors=colors, edgecolors='none', antialiased=True)
        ax.add_collection3d(mesh)

    axes = []

    # [Panel 1] Initial Point Cloud
    ax1 = fig.add_subplot(131, projection='3d')
    ax1.scatter(pc_3d[:,0], pc_3d[:,1], pc_3d[:,2], c='darkblue', s=0.5, alpha=0.8)
    format_ax(ax1, "a) Initial Point Cloud")
    axes.append(ax1)

    # [Panel 2] 2D Projections on Box Walls (Using find_contours)
    ax2 = fig.add_subplot(132, projection='3d')
    F_top, F_front, F_side = F_views

    # 1. Top View (Mapped to Floor: Z = bounds[0])
    for c in find_contours(F_top, 0.5):
        cx = bounds[0] + (c[:, 0] / (grid_size - 1)) * (bounds[1] - bounds[0])
        cy = bounds[0] + (c[:, 1] / (grid_size - 1)) * (bounds[1] - bounds[0])
        cz = np.full_like(cx, bounds[0])
        ax2.plot(cx, cy, cz, color='#7b1fa2', linewidth=1.5)

    # 2. Front View (Mapped to Back Wall: Y = bounds[1])
    for c in find_contours(F_front, 0.5):
        cx = bounds[0] + (c[:, 0] / (grid_size - 1)) * (bounds[1] - bounds[0])
        cz = bounds[0] + (c[:, 1] / (grid_size - 1)) * (bounds[1] - bounds[0])
        cy = np.full_like(cx, bounds[1])
        ax2.plot(cx, cy, cz, color='#1976d2', linewidth=1.5)

    # 3. Side View (Mapped to Left Wall: X = bounds[0])
    for c in find_contours(F_side, 0.5):
        cy = bounds[0] + (c[:, 0] / (grid_size - 1)) * (bounds[1] - bounds[0])
        cz = bounds[0] + (c[:, 1] / (grid_size - 1)) * (bounds[1] - bounds[0])
        cx = np.full_like(cy, bounds[0])
        ax2.plot(cx, cy, cz, color='#388e3c', linewidth=1.5)

    # Plot Point Cloud Shadows
    ax2.scatter(pc_3d[:,0], pc_3d[:,1], np.full(len(pc_3d), bounds[0]), c='gray', s=0.2, alpha=0.1)
    ax2.scatter(pc_3d[:,0], np.full(len(pc_3d), bounds[1]), pc_3d[:,2], c='gray', s=0.2, alpha=0.1)
    ax2.scatter(np.full(len(pc_3d), bounds[0]), pc_3d[:,1], pc_3d[:,2], c='gray', s=0.2, alpha=0.1)
    format_ax(ax2, "b) 2D Implicit Curves\n(Overlapped Projections)")
    axes.append(ax2)

    # [Panel 3] Final F_final + Point Cloud Overlap
    ax3 = fig.add_subplot(133, projection='3d')
    vf, ff = get_mesh(F_final)
    add_shaded_mesh(ax3, vf, ff, '#3cb371')
    ax3.scatter(pc_3d[:,0], pc_3d[:,1], pc_3d[:,2], c='darkblue', s=0.5, alpha=1.0)
    format_ax(ax3, "c) Final F_final\n(NeuSOGA Fusion)")
    axes.append(ax3)

    for ax in axes:
        ax.view_init(elev=view_elev, azim=view_azim)

    fig.canvas.draw()
    plt.tight_layout(pad=1.0)
    plt.savefig("NeuSOGA_Paper_Row_1x3.png", dpi=300, bbox_inches='tight')
    plt.show()
    print("  -> Saved 'NeuSOGA_Paper_Row_1x3.png'")

# =====================================================================
# 6. EXECUTION
# =====================================================================
if __name__ == "__main__":
    dataset_folder = download_modelnet40()
    h5_file = os.path.join(dataset_folder, "ply_data_train0.h5")
    predictor = initialize_sam()

    with h5py.File(h5_file, 'r') as f:
        point_clouds = f['data'][:]
        labels = f['label'][:]

    target_idx = np.where(labels == 0)[0][0]
    pc_3d = point_clouds[target_idx]

    pc_3d = pc_3d - np.mean(pc_3d, axis=0)
    pc_3d = pc_3d / np.max(np.linalg.norm(pc_3d, axis=1))

    # [CRITICAL FIX]: Align the airplane's physical "Up" to the Z-axis.
    pc_3d = pc_3d[:, [0, 2, 1]]

    grid_dim = 110

    print("\nStarting Pure Implicit NeuSOGA 3D Reconstruction...")
    F_final, F_x, F_y, F_z, F_views = run_pure_implicit_reconstruction(
        pc_3d, predictor, grid_size=grid_dim, num_slices=36, blend_eps=0.03
    )

    generate_1x3_paper_figure(pc_3d, F_final, F_views, grid_size=grid_dim, bounds=(-1.3, 1.3))